//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 01:52:47 PM PDT 
//


package org.yeastrc.proxl_import.api.xml_dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}crosslink_mass" maxOccurs="unbounded"/>
 *         &lt;element ref="{}cleaved_crosslink_mass" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crosslinkMass",
    "cleavedCrosslinkMass"
})
@XmlRootElement(name = "crosslink_masses")
public class CrosslinkMasses {

    @XmlElement(name = "crosslink_mass", required = true)
    protected List<CrosslinkMass> crosslinkMass;
    @XmlElement(name = "cleaved_crosslink_mass")
    protected List<CleavedCrosslinkMass> cleavedCrosslinkMass;

    /**
     * A full-length mass used for this linker in this search when both ends are bound to peptides--such as in crosslinks or looplinks Gets the value of the crosslinkMass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crosslinkMass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrosslinkMass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CrosslinkMass }
     * 
     * 
     */
    public List<CrosslinkMass> getCrosslinkMass() {
        if (crosslinkMass == null) {
            crosslinkMass = new ArrayList<CrosslinkMass>();
        }
        return this.crosslinkMass;
    }

    /**
     * Gets the value of the cleavedCrosslinkMass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cleavedCrosslinkMass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCleavedCrosslinkMass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CleavedCrosslinkMass }
     * 
     * 
     */
    public List<CleavedCrosslinkMass> getCleavedCrosslinkMass() {
        if (cleavedCrosslinkMass == null) {
            cleavedCrosslinkMass = new ArrayList<CleavedCrosslinkMass>();
        }
        return this.cleavedCrosslinkMass;
    }

}
