//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 09:30:24 AM PDT 
//


package org.yeastrc.proxl_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}residues" minOccurs="0"/>
 *         &lt;element ref="{}protein_termini" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "residues",
    "proteinTermini"
})
@XmlRootElement(name = "linked_end")
public class LinkedEnd {

    protected Residues residues;
    @XmlElement(name = "protein_termini")
    protected ProteinTermini proteinTermini;

    /**
     * A list of amino acid residues with which this end of the cross-linker may bind.
     * 
     * @return
     *     possible object is
     *     {@link Residues }
     *     
     */
    public Residues getResidues() {
        return residues;
    }

    /**
     * Sets the value of the residues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residues }
     *     
     */
    public void setResidues(Residues value) {
        this.residues = value;
    }

    /**
     * A list of protein terminal positions to which this cross-linker can bind. E.g. 0 or 1 residues away from n-terminus.
     * 
     * @return
     *     possible object is
     *     {@link ProteinTermini }
     *     
     */
    public ProteinTermini getProteinTermini() {
        return proteinTermini;
    }

    /**
     * Sets the value of the proteinTermini property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinTermini }
     *     
     */
    public void setProteinTermini(ProteinTermini value) {
        this.proteinTermini = value;
    }

}
