//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 01:52:47 PM PDT 
//


package org.yeastrc.proxl_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}residues" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="binds_protein_n_terminus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="binds_protein_c_terminus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "residues"
})
@XmlRootElement(name = "linked_end")
public class LinkedEnd {

    protected Residues residues;
    @XmlAttribute(name = "binds_protein_n_terminus")
    @XmlSchemaType(name = "anySimpleType")
    protected String bindsProteinNTerminus;
    @XmlAttribute(name = "binds_protein_c_terminus")
    @XmlSchemaType(name = "anySimpleType")
    protected String bindsProteinCTerminus;

    /**
     * A list of amino acid residues with which this end of the cross-linker may bind.
     * 
     * @return
     *     possible object is
     *     {@link Residues }
     *     
     */
    public Residues getResidues() {
        return residues;
    }

    /**
     * Sets the value of the residues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residues }
     *     
     */
    public void setResidues(Residues value) {
        this.residues = value;
    }

    /**
     * Gets the value of the bindsProteinNTerminus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindsProteinNTerminus() {
        return bindsProteinNTerminus;
    }

    /**
     * Sets the value of the bindsProteinNTerminus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindsProteinNTerminus(String value) {
        this.bindsProteinNTerminus = value;
    }

    /**
     * Gets the value of the bindsProteinCTerminus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindsProteinCTerminus() {
        return bindsProteinCTerminus;
    }

    /**
     * Sets the value of the bindsProteinCTerminus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindsProteinCTerminus(String value) {
        this.bindsProteinCTerminus = value;
    }

}
