//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.08 at 03:37:51 PM PST 
//


package org.yeastrc.proxl_import.api.xml_dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yeastrc.proxl_import.api.xml_dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileContent_QNAME = new QName("", "file_content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yeastrc.proxl_import.api.xml_dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Protein }
     * 
     */
    public Protein createProtein() {
        return new Protein();
    }

    /**
     * Create an instance of {@link SearchProgram }
     * 
     */
    public SearchProgram createSearchProgram() {
        return new SearchProgram();
    }

    /**
     * Create an instance of {@link Peptide }
     * 
     */
    public Peptide createPeptide() {
        return new Peptide();
    }

    /**
     * Create an instance of {@link Psm }
     * 
     */
    public Psm createPsm() {
        return new Psm();
    }

    /**
     * Create an instance of {@link ReportedPeptide }
     * 
     */
    public ReportedPeptide createReportedPeptide() {
        return new ReportedPeptide();
    }

    /**
     * Create an instance of {@link Psm.PerPeptideAnnotations }
     * 
     */
    public Psm.PerPeptideAnnotations createPsmPerPeptideAnnotations() {
        return new Psm.PerPeptideAnnotations();
    }

    /**
     * Create an instance of {@link Peptide.PeptideIsotopeLabels }
     * 
     */
    public Peptide.PeptideIsotopeLabels createPeptidePeptideIsotopeLabels() {
        return new Peptide.PeptideIsotopeLabels();
    }

    /**
     * Create an instance of {@link Protein.ProteinIsotopeLabels }
     * 
     */
    public Protein.ProteinIsotopeLabels createProteinProteinIsotopeLabels() {
        return new Protein.ProteinIsotopeLabels();
    }

    /**
     * Create an instance of {@link FilterablePsmPerPeptideAnnotationType }
     * 
     */
    public FilterablePsmPerPeptideAnnotationType createFilterablePsmPerPeptideAnnotationType() {
        return new FilterablePsmPerPeptideAnnotationType();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotationTypes }
     * 
     */
    public FilterablePsmAnnotationTypes createFilterablePsmAnnotationTypes() {
        return new FilterablePsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotationType }
     * 
     */
    public FilterablePsmAnnotationType createFilterablePsmAnnotationType() {
        return new FilterablePsmAnnotationType();
    }

    /**
     * Create an instance of {@link DescriptivePsmPerPeptideAnnotationTypes }
     * 
     */
    public DescriptivePsmPerPeptideAnnotationTypes createDescriptivePsmPerPeptideAnnotationTypes() {
        return new DescriptivePsmPerPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptivePsmPerPeptideAnnotationType }
     * 
     */
    public DescriptivePsmPerPeptideAnnotationType createDescriptivePsmPerPeptideAnnotationType() {
        return new DescriptivePsmPerPeptideAnnotationType();
    }

    /**
     * Create an instance of {@link ProteinAnnotation }
     * 
     */
    public ProteinAnnotation createProteinAnnotation() {
        return new ProteinAnnotation();
    }

    /**
     * Create an instance of {@link MonolinkMass }
     * 
     */
    public MonolinkMass createMonolinkMass() {
        return new MonolinkMass();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotations }
     * 
     */
    public DescriptivePsmAnnotations createDescriptivePsmAnnotations() {
        return new DescriptivePsmAnnotations();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotation }
     * 
     */
    public DescriptivePsmAnnotation createDescriptivePsmAnnotation() {
        return new DescriptivePsmAnnotation();
    }

    /**
     * Create an instance of {@link CleavedCrosslinkMass }
     * 
     */
    public CleavedCrosslinkMass createCleavedCrosslinkMass() {
        return new CleavedCrosslinkMass();
    }

    /**
     * Create an instance of {@link PsmAnnotationSortOrder }
     * 
     */
    public PsmAnnotationSortOrder createPsmAnnotationSortOrder() {
        return new PsmAnnotationSortOrder();
    }

    /**
     * Create an instance of {@link SearchAnnotation }
     * 
     */
    public SearchAnnotation createSearchAnnotation() {
        return new SearchAnnotation();
    }

    /**
     * Create an instance of {@link DecoyLabel }
     * 
     */
    public DecoyLabel createDecoyLabel() {
        return new DecoyLabel();
    }

    /**
     * Create an instance of {@link ConfigurationFiles }
     * 
     */
    public ConfigurationFiles createConfigurationFiles() {
        return new ConfigurationFiles();
    }

    /**
     * Create an instance of {@link ConfigurationFile }
     * 
     */
    public ConfigurationFile createConfigurationFile() {
        return new ConfigurationFile();
    }

    /**
     * Create an instance of {@link SearchProgramInfo }
     * 
     */
    public SearchProgramInfo createSearchProgramInfo() {
        return new SearchProgramInfo();
    }

    /**
     * Create an instance of {@link SearchPrograms }
     * 
     */
    public SearchPrograms createSearchPrograms() {
        return new SearchPrograms();
    }

    /**
     * Create an instance of {@link SearchProgram.PsmAnnotationTypes }
     * 
     */
    public SearchProgram.PsmAnnotationTypes createSearchProgramPsmAnnotationTypes() {
        return new SearchProgram.PsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link SearchProgram.PsmPerPeptideAnnotationTypes }
     * 
     */
    public SearchProgram.PsmPerPeptideAnnotationTypes createSearchProgramPsmPerPeptideAnnotationTypes() {
        return new SearchProgram.PsmPerPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link SearchProgram.ReportedPeptideAnnotationTypes }
     * 
     */
    public SearchProgram.ReportedPeptideAnnotationTypes createSearchProgramReportedPeptideAnnotationTypes() {
        return new SearchProgram.ReportedPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link AnnotationCutoffsOnImport }
     * 
     */
    public AnnotationCutoffsOnImport createAnnotationCutoffsOnImport() {
        return new AnnotationCutoffsOnImport();
    }

    /**
     * Create an instance of {@link PsmAnnotationCutoffsOnImport }
     * 
     */
    public PsmAnnotationCutoffsOnImport createPsmAnnotationCutoffsOnImport() {
        return new PsmAnnotationCutoffsOnImport();
    }

    /**
     * Create an instance of {@link SearchAnnotationCutoff }
     * 
     */
    public SearchAnnotationCutoff createSearchAnnotationCutoff() {
        return new SearchAnnotationCutoff();
    }

    /**
     * Create an instance of {@link ReportedPeptideAnnotationCutoffsOnImport }
     * 
     */
    public ReportedPeptideAnnotationCutoffsOnImport createReportedPeptideAnnotationCutoffsOnImport() {
        return new ReportedPeptideAnnotationCutoffsOnImport();
    }

    /**
     * Create an instance of {@link DefaultVisibleAnnotations }
     * 
     */
    public DefaultVisibleAnnotations createDefaultVisibleAnnotations() {
        return new DefaultVisibleAnnotations();
    }

    /**
     * Create an instance of {@link VisiblePsmAnnotations }
     * 
     */
    public VisiblePsmAnnotations createVisiblePsmAnnotations() {
        return new VisiblePsmAnnotations();
    }

    /**
     * Create an instance of {@link VisiblePsmPerPeptideAnnotations }
     * 
     */
    public VisiblePsmPerPeptideAnnotations createVisiblePsmPerPeptideAnnotations() {
        return new VisiblePsmPerPeptideAnnotations();
    }

    /**
     * Create an instance of {@link VisibleReportedPeptideAnnotations }
     * 
     */
    public VisibleReportedPeptideAnnotations createVisibleReportedPeptideAnnotations() {
        return new VisibleReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link AnnotationSortOrder }
     * 
     */
    public AnnotationSortOrder createAnnotationSortOrder() {
        return new AnnotationSortOrder();
    }

    /**
     * Create an instance of {@link ReportedPeptideAnnotationSortOrder }
     * 
     */
    public ReportedPeptideAnnotationSortOrder createReportedPeptideAnnotationSortOrder() {
        return new ReportedPeptideAnnotationSortOrder();
    }

    /**
     * Create an instance of {@link Modifications }
     * 
     */
    public Modifications createModifications() {
        return new Modifications();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link LinkedPositions }
     * 
     */
    public LinkedPositions createLinkedPositions() {
        return new LinkedPositions();
    }

    /**
     * Create an instance of {@link LinkedPosition }
     * 
     */
    public LinkedPosition createLinkedPosition() {
        return new LinkedPosition();
    }

    /**
     * Create an instance of {@link FilterablePsmPerPeptideAnnotationTypes }
     * 
     */
    public FilterablePsmPerPeptideAnnotationTypes createFilterablePsmPerPeptideAnnotationTypes() {
        return new FilterablePsmPerPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link Linkers }
     * 
     */
    public Linkers createLinkers() {
        return new Linkers();
    }

    /**
     * Create an instance of {@link Linker }
     * 
     */
    public Linker createLinker() {
        return new Linker();
    }

    /**
     * Create an instance of {@link MonolinkMasses }
     * 
     */
    public MonolinkMasses createMonolinkMasses() {
        return new MonolinkMasses();
    }

    /**
     * Create an instance of {@link CrosslinkMasses }
     * 
     */
    public CrosslinkMasses createCrosslinkMasses() {
        return new CrosslinkMasses();
    }

    /**
     * Create an instance of {@link CrosslinkMass }
     * 
     */
    public CrosslinkMass createCrosslinkMass() {
        return new CrosslinkMass();
    }

    /**
     * Create an instance of {@link ReportedPeptides }
     * 
     */
    public ReportedPeptides createReportedPeptides() {
        return new ReportedPeptides();
    }

    /**
     * Create an instance of {@link Peptides }
     * 
     */
    public Peptides createPeptides() {
        return new Peptides();
    }

    /**
     * Create an instance of {@link Psms }
     * 
     */
    public Psms createPsms() {
        return new Psms();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotations }
     * 
     */
    public FilterablePsmAnnotations createFilterablePsmAnnotations() {
        return new FilterablePsmAnnotations();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotation }
     * 
     */
    public FilterablePsmAnnotation createFilterablePsmAnnotation() {
        return new FilterablePsmAnnotation();
    }

    /**
     * Create an instance of {@link ReportedPeptide.ReportedPeptideAnnotations }
     * 
     */
    public ReportedPeptide.ReportedPeptideAnnotations createReportedPeptideReportedPeptideAnnotations() {
        return new ReportedPeptide.ReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link FilterablePsmPerPeptideAnnotation }
     * 
     */
    public FilterablePsmPerPeptideAnnotation createFilterablePsmPerPeptideAnnotation() {
        return new FilterablePsmPerPeptideAnnotation();
    }

    /**
     * Create an instance of {@link DescriptivePeptideAnnotationType }
     * 
     */
    public DescriptivePeptideAnnotationType createDescriptivePeptideAnnotationType() {
        return new DescriptivePeptideAnnotationType();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotations }
     * 
     */
    public DescriptiveReportedPeptideAnnotations createDescriptiveReportedPeptideAnnotations() {
        return new DescriptiveReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotation }
     * 
     */
    public DescriptiveReportedPeptideAnnotation createDescriptiveReportedPeptideAnnotation() {
        return new DescriptiveReportedPeptideAnnotation();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotationTypes }
     * 
     */
    public DescriptivePsmAnnotationTypes createDescriptivePsmAnnotationTypes() {
        return new DescriptivePsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotationType }
     * 
     */
    public DescriptivePsmAnnotationType createDescriptivePsmAnnotationType() {
        return new DescriptivePsmAnnotationType();
    }

    /**
     * Create an instance of {@link DescriptivePsmPerPeptideAnnotation }
     * 
     */
    public DescriptivePsmPerPeptideAnnotation createDescriptivePsmPerPeptideAnnotation() {
        return new DescriptivePsmPerPeptideAnnotation();
    }

    /**
     * Create an instance of {@link DescriptivePsmPerPeptideAnnotations }
     * 
     */
    public DescriptivePsmPerPeptideAnnotations createDescriptivePsmPerPeptideAnnotations() {
        return new DescriptivePsmPerPeptideAnnotations();
    }

    /**
     * Create an instance of {@link DescriptivePeptideAnnotationTypes }
     * 
     */
    public DescriptivePeptideAnnotationTypes createDescriptivePeptideAnnotationTypes() {
        return new DescriptivePeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotations }
     * 
     */
    public FilterableReportedPeptideAnnotations createFilterableReportedPeptideAnnotations() {
        return new FilterableReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotation }
     * 
     */
    public FilterableReportedPeptideAnnotation createFilterableReportedPeptideAnnotation() {
        return new FilterableReportedPeptideAnnotation();
    }

    /**
     * Create an instance of {@link FilterablePeptideAnnotationTypes }
     * 
     */
    public FilterablePeptideAnnotationTypes createFilterablePeptideAnnotationTypes() {
        return new FilterablePeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link FilterablePeptideAnnotationType }
     * 
     */
    public FilterablePeptideAnnotationType createFilterablePeptideAnnotationType() {
        return new FilterablePeptideAnnotationType();
    }

    /**
     * Create an instance of {@link DecoyLabels }
     * 
     */
    public DecoyLabels createDecoyLabels() {
        return new DecoyLabels();
    }

    /**
     * Create an instance of {@link ProxlInput }
     * 
     */
    public ProxlInput createProxlInput() {
        return new ProxlInput();
    }

    /**
     * Create an instance of {@link MatchedProteins }
     * 
     */
    public MatchedProteins createMatchedProteins() {
        return new MatchedProteins();
    }

    /**
     * Create an instance of {@link StaticModifications }
     * 
     */
    public StaticModifications createStaticModifications() {
        return new StaticModifications();
    }

    /**
     * Create an instance of {@link StaticModification }
     * 
     */
    public StaticModification createStaticModification() {
        return new StaticModification();
    }

    /**
     * Create an instance of {@link FilterablePsmPerPeptideAnnotations }
     * 
     */
    public FilterablePsmPerPeptideAnnotations createFilterablePsmPerPeptideAnnotations() {
        return new FilterablePsmPerPeptideAnnotations();
    }

    /**
     * Create an instance of {@link Psm.PerPeptideAnnotations.PsmPeptide }
     * 
     */
    public Psm.PerPeptideAnnotations.PsmPeptide createPsmPerPeptideAnnotationsPsmPeptide() {
        return new Psm.PerPeptideAnnotations.PsmPeptide();
    }

    /**
     * Create an instance of {@link Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel }
     * 
     */
    public Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel createPeptidePeptideIsotopeLabelsPeptideIsotopeLabel() {
        return new Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel();
    }

    /**
     * Create an instance of {@link Protein.ProteinIsotopeLabels.ProteinIsotopeLabel }
     * 
     */
    public Protein.ProteinIsotopeLabels.ProteinIsotopeLabel createProteinProteinIsotopeLabelsProteinIsotopeLabel() {
        return new Protein.ProteinIsotopeLabels.ProteinIsotopeLabel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file_content")
    public JAXBElement<byte[]> createFileContent(byte[] value) {
        return new JAXBElement<byte[]>(_FileContent_QNAME, byte[].class, null, ((byte[]) value));
    }

}
