//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.08 at 04:29:21 PM PST 
//


package org.yeastrc.proxl_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}modifications" minOccurs="0"/>
 *         &lt;element ref="{}linked_positions" minOccurs="0"/>
 *         &lt;element name="peptide_isotope_labels" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="peptide_isotope_label" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="sequence" use="required" type="{}sequence_type" />
 *       &lt;attribute name="unique_id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modifications",
    "linkedPositions",
    "peptideIsotopeLabels"
})
@XmlRootElement(name = "peptide")
public class Peptide {

    protected Modifications modifications;
    @XmlElement(name = "linked_positions")
    protected LinkedPositions linkedPositions;
    @XmlElement(name = "peptide_isotope_labels")
    protected Peptide.PeptideIsotopeLabels peptideIsotopeLabels;
    @XmlAttribute(name = "sequence", required = true)
    protected String sequence;
    @XmlAttribute(name = "unique_id")
    @XmlSchemaType(name = "anySimpleType")
    protected String uniqueId;

    /**
     * Gets the value of the modifications property.
     * 
     * @return
     *     possible object is
     *     {@link Modifications }
     *     
     */
    public Modifications getModifications() {
        return modifications;
    }

    /**
     * Sets the value of the modifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modifications }
     *     
     */
    public void setModifications(Modifications value) {
        this.modifications = value;
    }

    /**
     * The list of linked positions in a peptide. Do not include monolinks here, they are listed as modifications in the modifications element. Only list looplinked and crosslinked positions.
     * 
     * @return
     *     possible object is
     *     {@link LinkedPositions }
     *     
     */
    public LinkedPositions getLinkedPositions() {
        return linkedPositions;
    }

    /**
     * Sets the value of the linkedPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedPositions }
     *     
     */
    public void setLinkedPositions(LinkedPositions value) {
        this.linkedPositions = value;
    }

    /**
     * Gets the value of the peptideIsotopeLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Peptide.PeptideIsotopeLabels }
     *     
     */
    public Peptide.PeptideIsotopeLabels getPeptideIsotopeLabels() {
        return peptideIsotopeLabels;
    }

    /**
     * Sets the value of the peptideIsotopeLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Peptide.PeptideIsotopeLabels }
     *     
     */
    public void setPeptideIsotopeLabels(Peptide.PeptideIsotopeLabels value) {
        this.peptideIsotopeLabels = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueId(String value) {
        this.uniqueId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="peptide_isotope_label" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "peptideIsotopeLabel"
    })
    public static class PeptideIsotopeLabels {

        @XmlElement(name = "peptide_isotope_label")
        protected Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel peptideIsotopeLabel;

        /**
         * Gets the value of the peptideIsotopeLabel property.
         * 
         * @return
         *     possible object is
         *     {@link Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel }
         *     
         */
        public Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel getPeptideIsotopeLabel() {
            return peptideIsotopeLabel;
        }

        /**
         * Sets the value of the peptideIsotopeLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel }
         *     
         */
        public void setPeptideIsotopeLabel(Peptide.PeptideIsotopeLabels.PeptideIsotopeLabel value) {
            this.peptideIsotopeLabel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PeptideIsotopeLabel {

            @XmlAttribute(name = "label", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String label;

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

        }

    }

}
