//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 09:30:24 AM PDT 
//


package org.yeastrc.proxl_import.api.xml_dto;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="terminus_end" use="required" type="{}protein_terminus_designation" />
 *       &lt;attribute name="distance_from_terminus" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "protein_terminus")
public class ProteinTerminus {

    @XmlAttribute(name = "terminus_end", required = true)
    protected ProteinTerminusDesignation terminusEnd;
    @XmlAttribute(name = "distance_from_terminus", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger distanceFromTerminus;

    /**
     * Gets the value of the terminusEnd property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinTerminusDesignation }
     *     
     */
    public ProteinTerminusDesignation getTerminusEnd() {
        return terminusEnd;
    }

    /**
     * Sets the value of the terminusEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinTerminusDesignation }
     *     
     */
    public void setTerminusEnd(ProteinTerminusDesignation value) {
        this.terminusEnd = value;
    }

    /**
     * Gets the value of the distanceFromTerminus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistanceFromTerminus() {
        return distanceFromTerminus;
    }

    /**
     * Sets the value of the distanceFromTerminus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDistanceFromTerminus(BigInteger value) {
        this.distanceFromTerminus = value;
    }

}
