//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:20:46 PM PDT 
//


package org.yeastrc.proxl_import.api.xml_dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}protein_annotation" maxOccurs="unbounded"/>
 *         &lt;element name="protein_isotope_labels" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="protein_isotope_label" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="sequence" use="required" type="{}sequence_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proteinAnnotation",
    "proteinIsotopeLabels"
})
@XmlRootElement(name = "protein")
public class Protein {

    @XmlElement(name = "protein_annotation", required = true)
    protected List<ProteinAnnotation> proteinAnnotation;
    @XmlElement(name = "protein_isotope_labels")
    protected Protein.ProteinIsotopeLabels proteinIsotopeLabels;
    @XmlAttribute(name = "sequence", required = true)
    protected String sequence;

    /**
     * Annotations for this sequence from the sequence database used to search the data. Since there may be multiple annotations for a single sequence (as separated by control-A characters in a FASTA file), each annotation should appear hear associated with a single protein.Gets the value of the proteinAnnotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proteinAnnotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProteinAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProteinAnnotation }
     * 
     * 
     */
    public List<ProteinAnnotation> getProteinAnnotation() {
        if (proteinAnnotation == null) {
            proteinAnnotation = new ArrayList<ProteinAnnotation>();
        }
        return this.proteinAnnotation;
    }

    /**
     * Gets the value of the proteinIsotopeLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Protein.ProteinIsotopeLabels }
     *     
     */
    public Protein.ProteinIsotopeLabels getProteinIsotopeLabels() {
        return proteinIsotopeLabels;
    }

    /**
     * Sets the value of the proteinIsotopeLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Protein.ProteinIsotopeLabels }
     *     
     */
    public void setProteinIsotopeLabels(Protein.ProteinIsotopeLabels value) {
        this.proteinIsotopeLabels = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="protein_isotope_label" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proteinIsotopeLabel"
    })
    public static class ProteinIsotopeLabels {

        @XmlElement(name = "protein_isotope_label")
        protected Protein.ProteinIsotopeLabels.ProteinIsotopeLabel proteinIsotopeLabel;

        /**
         * Gets the value of the proteinIsotopeLabel property.
         * 
         * @return
         *     possible object is
         *     {@link Protein.ProteinIsotopeLabels.ProteinIsotopeLabel }
         *     
         */
        public Protein.ProteinIsotopeLabels.ProteinIsotopeLabel getProteinIsotopeLabel() {
            return proteinIsotopeLabel;
        }

        /**
         * Sets the value of the proteinIsotopeLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Protein.ProteinIsotopeLabels.ProteinIsotopeLabel }
         *     
         */
        public void setProteinIsotopeLabel(Protein.ProteinIsotopeLabels.ProteinIsotopeLabel value) {
            this.proteinIsotopeLabel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ProteinIsotopeLabel {

            @XmlAttribute(name = "label", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String label;

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

        }

    }

}
