//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 10:38:02 AM PST 
//


package org.yeastrc.proxl_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="psm_annotation_types">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}filterable_psm_annotation_types"/>
 *                   &lt;element ref="{}descriptive_psm_annotation_types" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="psm_per_peptide_annotation_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}filterable_psm_per_peptide_annotation_types"/>
 *                   &lt;element ref="{}descriptive_psm_per_peptide_annotation_types" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reported_peptide_annotation_types" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}filterable_peptide_annotation_types" minOccurs="0"/>
 *                   &lt;element ref="{}descriptive_peptide_annotation_types" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="display_name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psmAnnotationTypes",
    "psmPerPeptideAnnotationTypes",
    "reportedPeptideAnnotationTypes"
})
@XmlRootElement(name = "search_program")
public class SearchProgram {

    @XmlElement(name = "psm_annotation_types", required = true)
    protected SearchProgram.PsmAnnotationTypes psmAnnotationTypes;
    @XmlElement(name = "psm_per_peptide_annotation_types")
    protected SearchProgram.PsmPerPeptideAnnotationTypes psmPerPeptideAnnotationTypes;
    @XmlElement(name = "reported_peptide_annotation_types")
    protected SearchProgram.ReportedPeptideAnnotationTypes reportedPeptideAnnotationTypes;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "display_name")
    @XmlSchemaType(name = "anySimpleType")
    protected String displayName;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the psmAnnotationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SearchProgram.PsmAnnotationTypes }
     *     
     */
    public SearchProgram.PsmAnnotationTypes getPsmAnnotationTypes() {
        return psmAnnotationTypes;
    }

    /**
     * Sets the value of the psmAnnotationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchProgram.PsmAnnotationTypes }
     *     
     */
    public void setPsmAnnotationTypes(SearchProgram.PsmAnnotationTypes value) {
        this.psmAnnotationTypes = value;
    }

    /**
     * Gets the value of the psmPerPeptideAnnotationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SearchProgram.PsmPerPeptideAnnotationTypes }
     *     
     */
    public SearchProgram.PsmPerPeptideAnnotationTypes getPsmPerPeptideAnnotationTypes() {
        return psmPerPeptideAnnotationTypes;
    }

    /**
     * Sets the value of the psmPerPeptideAnnotationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchProgram.PsmPerPeptideAnnotationTypes }
     *     
     */
    public void setPsmPerPeptideAnnotationTypes(SearchProgram.PsmPerPeptideAnnotationTypes value) {
        this.psmPerPeptideAnnotationTypes = value;
    }

    /**
     * Gets the value of the reportedPeptideAnnotationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SearchProgram.ReportedPeptideAnnotationTypes }
     *     
     */
    public SearchProgram.ReportedPeptideAnnotationTypes getReportedPeptideAnnotationTypes() {
        return reportedPeptideAnnotationTypes;
    }

    /**
     * Sets the value of the reportedPeptideAnnotationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchProgram.ReportedPeptideAnnotationTypes }
     *     
     */
    public void setReportedPeptideAnnotationTypes(SearchProgram.ReportedPeptideAnnotationTypes value) {
        this.reportedPeptideAnnotationTypes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}filterable_psm_annotation_types"/>
     *         &lt;element ref="{}descriptive_psm_annotation_types" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filterablePsmAnnotationTypes",
        "descriptivePsmAnnotationTypes"
    })
    public static class PsmAnnotationTypes {

        @XmlElement(name = "filterable_psm_annotation_types", required = true)
        protected FilterablePsmAnnotationTypes filterablePsmAnnotationTypes;
        @XmlElement(name = "descriptive_psm_annotation_types")
        protected DescriptivePsmAnnotationTypes descriptivePsmAnnotationTypes;

        /**
         * Gets the value of the filterablePsmAnnotationTypes property.
         * 
         * @return
         *     possible object is
         *     {@link FilterablePsmAnnotationTypes }
         *     
         */
        public FilterablePsmAnnotationTypes getFilterablePsmAnnotationTypes() {
            return filterablePsmAnnotationTypes;
        }

        /**
         * Sets the value of the filterablePsmAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilterablePsmAnnotationTypes }
         *     
         */
        public void setFilterablePsmAnnotationTypes(FilterablePsmAnnotationTypes value) {
            this.filterablePsmAnnotationTypes = value;
        }

        /**
         * Gets the value of the descriptivePsmAnnotationTypes property.
         * 
         * @return
         *     possible object is
         *     {@link DescriptivePsmAnnotationTypes }
         *     
         */
        public DescriptivePsmAnnotationTypes getDescriptivePsmAnnotationTypes() {
            return descriptivePsmAnnotationTypes;
        }

        /**
         * Sets the value of the descriptivePsmAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DescriptivePsmAnnotationTypes }
         *     
         */
        public void setDescriptivePsmAnnotationTypes(DescriptivePsmAnnotationTypes value) {
            this.descriptivePsmAnnotationTypes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}filterable_psm_per_peptide_annotation_types"/>
     *         &lt;element ref="{}descriptive_psm_per_peptide_annotation_types" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filterablePsmPerPeptideAnnotationTypes",
        "descriptivePsmPerPeptideAnnotationTypes"
    })
    public static class PsmPerPeptideAnnotationTypes {

        @XmlElement(name = "filterable_psm_per_peptide_annotation_types", required = true)
        protected FilterablePsmPerPeptideAnnotationTypes filterablePsmPerPeptideAnnotationTypes;
        @XmlElement(name = "descriptive_psm_per_peptide_annotation_types")
        protected DescriptivePsmPerPeptideAnnotationTypes descriptivePsmPerPeptideAnnotationTypes;

        /**
         * If the search program supports it, the collection of numeric annotation types (such as scores) that may be associated with a each separate peptide that is part that are part of a single PSM (e.g. two cross-linked PSMs)
         * 
         * @return
         *     possible object is
         *     {@link FilterablePsmPerPeptideAnnotationTypes }
         *     
         */
        public FilterablePsmPerPeptideAnnotationTypes getFilterablePsmPerPeptideAnnotationTypes() {
            return filterablePsmPerPeptideAnnotationTypes;
        }

        /**
         * Sets the value of the filterablePsmPerPeptideAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilterablePsmPerPeptideAnnotationTypes }
         *     
         */
        public void setFilterablePsmPerPeptideAnnotationTypes(FilterablePsmPerPeptideAnnotationTypes value) {
            this.filterablePsmPerPeptideAnnotationTypes = value;
        }

        /**
         * Optional. The collection of annotation types associated with each separate peptide that is part of a single PSM that are descriptive or not meant to be used to filter based on quality
         * 
         * @return
         *     possible object is
         *     {@link DescriptivePsmPerPeptideAnnotationTypes }
         *     
         */
        public DescriptivePsmPerPeptideAnnotationTypes getDescriptivePsmPerPeptideAnnotationTypes() {
            return descriptivePsmPerPeptideAnnotationTypes;
        }

        /**
         * Sets the value of the descriptivePsmPerPeptideAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DescriptivePsmPerPeptideAnnotationTypes }
         *     
         */
        public void setDescriptivePsmPerPeptideAnnotationTypes(DescriptivePsmPerPeptideAnnotationTypes value) {
            this.descriptivePsmPerPeptideAnnotationTypes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}filterable_peptide_annotation_types" minOccurs="0"/>
     *         &lt;element ref="{}descriptive_peptide_annotation_types" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filterablePeptideAnnotationTypes",
        "descriptivePeptideAnnotationTypes"
    })
    public static class ReportedPeptideAnnotationTypes {

        @XmlElement(name = "filterable_peptide_annotation_types")
        protected FilterablePeptideAnnotationTypes filterablePeptideAnnotationTypes;
        @XmlElement(name = "descriptive_peptide_annotation_types")
        protected DescriptivePeptideAnnotationTypes descriptivePeptideAnnotationTypes;

        /**
         * Gets the value of the filterablePeptideAnnotationTypes property.
         * 
         * @return
         *     possible object is
         *     {@link FilterablePeptideAnnotationTypes }
         *     
         */
        public FilterablePeptideAnnotationTypes getFilterablePeptideAnnotationTypes() {
            return filterablePeptideAnnotationTypes;
        }

        /**
         * Sets the value of the filterablePeptideAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilterablePeptideAnnotationTypes }
         *     
         */
        public void setFilterablePeptideAnnotationTypes(FilterablePeptideAnnotationTypes value) {
            this.filterablePeptideAnnotationTypes = value;
        }

        /**
         * Gets the value of the descriptivePeptideAnnotationTypes property.
         * 
         * @return
         *     possible object is
         *     {@link DescriptivePeptideAnnotationTypes }
         *     
         */
        public DescriptivePeptideAnnotationTypes getDescriptivePeptideAnnotationTypes() {
            return descriptivePeptideAnnotationTypes;
        }

        /**
         * Sets the value of the descriptivePeptideAnnotationTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DescriptivePeptideAnnotationTypes }
         *     
         */
        public void setDescriptivePeptideAnnotationTypes(DescriptivePeptideAnnotationTypes value) {
            this.descriptivePeptideAnnotationTypes = value;
        }

    }

}
