
name: Build and run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '${{matrix.jdk}}'
        distribution: 'adopt'
    - name: Remove and remake the jaxb-generated dir
      run: rm -rf src_java_jaxb_classes_from_xsd && mkdir src_java_jaxb_classes_from_xsd
    - name: Generate jaxb-generated files
      run: xjc -d src_java_jaxb_classes_from_xsd -p org.yeastrc.proxl_import.api.xml_dto xsd/proxl-xml.xsd
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
