name: Release Workflow

on:
  release:
    types: [released]
    tags:
      - 'v*'

env:
  LIB_JAR: "proxl-import-api.jar"
  XSD_FILE: "proxl-xml.xsd"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Remove and remake the jaxb-generated dir
        run: rm -rf src_java_jaxb_classes_from_xsd && mkdir src_java_jaxb_classes_from_xsd
      - name: Generate jaxb-generated files
        run: xjc -d src_java_jaxb_classes_from_xsd -p org.yeastrc.proxl_import.api.xml_dto xsd/proxl-xml.xsd
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload lib jar to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/${{ env.LIB_JAR }}
          asset_name: ${{ env.LIB_JAR }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
      - name: Upload xsd to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xsd/${{ env.XSD_FILE }}
          asset_name: ${{ env.XSD_FILE }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Switch to repository branch
        run: git stash && git fetch && git checkout repository
      - name: Publish to local maven repo
        run: mvn install:install-file -DgroupId=org.yeastrc -DartifactId=proxl-import-api -Dversion=${{ steps.get_version.outputs.VERSION }} -Dfile=build/libs/${{ env.LIB_JAR }} -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=.  -DcreateChecksum=true
      - name: Commit local maven repo update
        run: |
          git config --global user.name 'GitHub Release Action'
          git config --global user.email 'mriffle@users.noreply.github.com'
          git add org/yeastrc/proxl-import-api
          git commit -am "Automated commit from release GitHub Action"
          git push
